package verification.parser;

public class JsonKeyName {
	public static final String ABSOLUTE = "absolute";
	public static final String APPLYPARAMS = "applyParams";
	public static final String ARGUMENTS = "arguments";
	public static final String BASE = "base";
	public static final String BODY = "body";
	public static final String COMPONENTS = "components";
	public static final String CONTROLLOCALS = "controlLocals";
	public static final String DECLARATIONS = "declarations";
	public static final String DEFAULTEXPRESSION = "DefaultExpression";
	public static final String DIRECTION = "direction";
	public static final String EXPR = "expr";
	public static final String FIELDs = "fields";
	public static final String ISSIGNED = "isSigned";
	public static final String KEYSET = "keyset";
	public static final String MEMBER = "member";
	public static final String METHOD = "method";
	public static final String METHODCALL = "methodCall";
	public static final String NAME = "name";
	public static final String NODE_TYPE = "Node_Type";
	public static final String PARAMETER = "Parameter";
	public static final String PARAMETERS = "parameters";
	public static final String PARSERLOCALS = "parserLocals";
	public static final String PARSERSTATE = "parserState";
	public static final String PATH = "path";
	public static final String SELECT = "select";
	public static final String SELECTCASES = "selectCases";
	public static final String SELECTEXPRESSION = "selectExpression";
	public static final String SIZE = "size";
	public static final String STATE = "state";
	public static final String STATES = "states";
	public static final String TYPE = "type";
	public static final String TYPEARGUMENTS = "typeArguments";
	public static final String VALUE = "value";
	public static final String VEC = "vec";
	public static final String NODE_ID = "Node_ID";
	public static final String LEFT = "left";
	public static final String RIGHT = "right";
}
